package com.projectx.game.input.motor

import com.google.gson.JsonObject
import com.google.gson.JsonParser
import java.io.File
import kotlin.math.abs
import kotlin.math.hypot
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Pins the engine's step encoding to the training one.
 *
 * The Kotlin side builds its own step vector from (remaining, velocity, elapsed, total), which is a second
 * implementation of what `motor_dataset.encode_reach` does in Python. A silent disagreement there does not
 * crash — it produces motion that is subtly not this player's, which is the single failure mode the whole
 * pipeline exists to prevent, and the same class of bug that already bit the earlier encoder.
 *
 * The fixture is generated by `ai-input/spec/generate_motor_fixture.py`.
 */
class MotorParityTest {
    private val tolerance = 1e-5f

    private val fixture: JsonObject by lazy {
        JsonParser.parseString(specFile("motor_fixture.json").readText()).asJsonObject
    }

    @Test
    fun `step feature order matches the training encoder`() {
        val expected = fixture["step_features"].asJsonArray.map { it.asString }
        val contract = MotorContract.load(modelContract())
        assertEquals(
            expected, contract.stepFeatures,
            "the exported contract's feature order differs from the encoder that produced the fixture"
        )
    }

    @Test
    fun `the pacing constant matches the one the model was trained with`() {
        val contract = MotorContract.load(modelContract())
        assertEquals(
            fixture["nominal_reach_ms"].asFloat, contract.nominalReachMs,
            "elapsed-time scaling differs, so the model's pacing means something different at inference"
        )
    }

    /**
     * The step vector is what the engine actually hands the graph. Building it wrongly is invisible at
     * runtime, so it is checked against values produced by the training code for the same state.
     */
    @Test
    fun `kotlin builds the same step vector as the trainer`() {
        val contract = MotorContract.load(modelContract())
        for (element in fixture["cases"].asJsonArray) {
            val case = element.asJsonObject
            val remaining = case["remaining"].asJsonArray
            val velocity = case["velocity"].asJsonArray
            val expected = case["expected_step"].asJsonArray

            val built = FloatArray(contract.stepDim)
            val rx = remaining[0].asFloat
            val ry = remaining[1].asFloat
            built[contract.indexOf("remaining_x")] = rx
            built[contract.indexOf("remaining_y")] = ry
            built[contract.indexOf("remaining_dist")] = hypot(rx.toDouble(), ry.toDouble()).toFloat()
            built[contract.indexOf("velocity_x")] = velocity[0].asFloat
            built[contract.indexOf("velocity_y")] = velocity[1].asFloat
            built[contract.indexOf("elapsed_frac")] = case["elapsed_ms"].asFloat / contract.nominalReachMs
            built[contract.indexOf("total_dist")] = case["total_distance"].asFloat

            for (i in 0 until contract.stepDim) {
                val want = expected[i].asFloat
                if (abs(want - built[i]) > tolerance) {
                    fail(
                        "${case["why"].asString}: feature ${contract.stepFeatures[i]} " +
                            "expected $want but built ${built[i]}"
                    )
                }
            }
        }
    }

    private fun modelContract(): File {
        val file = specFile("motor_contract_reference.json")
        if (file.isFile) return file
        // The exporter writes the contract beside the model rather than into the spec directory, so fall back
        // to a trained player's copy when one exists on this machine.
        val local = File(System.getProperty("user.home"), ".projectx/models")
            .listFiles()?.asSequence()
            ?.map { File(it, MotorContract.FILENAME) }
            ?.firstOrNull { it.isFile }
        assertTrue(
            local != null,
            "no motor contract available — export a model with ai-input/export_motor_onnx.py"
        )
        return local!!
    }

    private fun specFile(name: String): File {
        val file = File(repositoryRoot(), "ai-input/spec/$name")
        assertTrue(file.isFile, "$name is missing — run ai-input/spec/generate_motor_fixture.py")
        return file
    }

    private fun repositoryRoot(): File {
        var candidate: File? = File("").absoluteFile
        while (candidate != null) {
            if (File(candidate, "ai-input/spec").isDirectory) return candidate
            candidate = candidate.parentFile
        }
        error("could not locate the repository root from ${File("").absolutePath}")
    }
}
