package com.projectx.game.input

import com.google.gson.JsonObject
import com.google.gson.JsonParser
import java.io.File
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Pins the engine's encoder to the training encoder. The two are separate implementations in separate
 * languages fed to the same model, and they have silently disagreed before — on the action-label order, on
 * whether long deltas get clipped, on which column holds what. The fixture is generated by
 * `ai-input/spec/generate_fixtures.py` from `ai-input/encode.py`, so a change on either side that is not
 * mirrored fails here rather than degrading the model in the field.
 *
 * Deliberately checkpoint-independent: it asserts the encoding, so retraining never invalidates it.
 */
class InputContractParityTest {
    private val tolerance = 1e-6f

    private val contract: InputContract by lazy { InputContract.load(specFile("io_contract.json")) }
    private val fixture: JsonObject by lazy {
        JsonParser.parseString(specFile("encoder_fixture.json").readText()).asJsonObject
    }

    @Test
    fun `fixture was generated from the same contract version`() {
        assertEquals(
            contract.contractVersion,
            fixture["contract_version"].asInt,
            "encoder_fixture.json is stale — rerun ai-input/spec/generate_fixtures.py"
        )
        assertEquals(contract.windowSize, fixture["window_size"].asInt)
        assertEquals(contract.featureDim, fixture["feature_dim"].asInt)
        assertEquals(
            contract.features.map { it.name },
            fixture["feature_names"].asJsonArray.map { it.asString },
            "feature order differs between the contract and the fixture"
        )
    }

    @Test
    fun `every action label the model can emit decodes to a name or to null`() {
        for (index in 0 until contract.actionHeadWidth) {
            val label = contract.actionLabelOrNull(index)
            if (index < contract.actionLabels.size) {
                assertEquals(contract.actionLabels[index], label)
            } else {
                assertTrue(label == null, "untrained head slot $index must not decode to an action")
            }
        }
    }

    @Test
    fun `kotlin encoder reproduces every python fixture case`() {
        val encoder = InputFeatureEncoder(contract)
        val cases = fixture["cases"].asJsonArray
        assertTrue(cases.size() > 0, "fixture has no cases")

        for (element in cases) {
            val case = element.asJsonObject
            val name = case["name"].asString
            val context = gameContext(case["context"].asJsonObject)
            val events = case["events"].asJsonArray.map { inputEvent(it.asJsonObject) }

            val actual = encoder.encodeWindow(events, context)
            val expected = case["expected_window"].asJsonArray
            assertEquals(contract.windowSize, expected.size(), "$name: row count")

            for (row in 0 until contract.windowSize) {
                val expectedRow = expected[row].asJsonArray
                for (column in 0 until contract.featureDim) {
                    val want = expectedRow[column].asFloat
                    val got = actual[row * contract.featureDim + column]
                    if (abs(want - got) > tolerance) {
                        fail(
                            "$name (${case["why"].asString}): row $row column $column " +
                                "'${contract.features[column].name}' expected $want but encoded $got"
                        )
                    }
                }
            }

            val actualContext = encoder.contextVector(actual)
            val expectedContext = case["expected_context"].asJsonArray
            assertEquals(contract.contextDim, expectedContext.size(), "$name: context width")
            for (i in 0 until contract.contextDim) {
                val want = expectedContext[i].asFloat
                if (abs(want - actualContext[i]) > tolerance) {
                    fail("$name: context $i expected $want but encoded ${actualContext[i]}")
                }
            }
        }
    }

    private fun gameContext(json: JsonObject) = GameContext(
        gameTick = 0,
        mainState = json["main_state"].asInt,
        playerX = json["player_tile_x"].asInt,
        playerY = json["player_tile_y"].asInt,
        playerPlane = 0,
        timestampNanos = 0L,
    )

    private fun inputEvent(json: JsonObject): InputEvent {
        val timestampNanos = json["timestamp_nanos"].asLong
        val gameTick = json["game_tick"].asInt
        return when (val type = json["type"].asString) {
            "mouse_motion" -> MouseMotionEvent(timestampNanos, gameTick, json["x"].asInt, json["y"].asInt)
            "mouse_button" -> MouseButtonEvent(
                timestampNanos = timestampNanos,
                gameTick = gameTick,
                x = json["x"].asInt,
                y = json["y"].asInt,
                button = MouseButton.fromId(json["button"].asInt)
                    ?: error("fixture has unknown button id ${json["button"].asInt}"),
                pressed = json["pressed"].asBoolean,
            )
            "mouse_scroll" -> MouseScrollEvent(
                timestampNanos = timestampNanos,
                gameTick = gameTick,
                x = json["x"].asInt,
                y = json["y"].asInt,
                scrollDelta = json["scroll_delta"].asInt,
            )
            "keyboard" -> KeyboardEvent(
                timestampNanos = timestampNanos,
                gameTick = gameTick,
                keyCode = json["key_code"].asInt,
                pressed = json["pressed"].asBoolean,
            )
            else -> error("fixture has unknown event type '$type'")
        }
    }

    private fun specFile(name: String): File {
        val file = File(repositoryRoot(), "ai-input/spec/$name")
        assertTrue(
            file.isFile,
            "$name is missing — the ai-input submodule is not checked out (git submodule update --init --recursive)"
        )
        return file
    }

    private fun repositoryRoot(): File {
        var candidate: File? = File("").absoluteFile
        while (candidate != null) {
            if (File(candidate, "ai-input/spec").isDirectory) return candidate
            candidate = candidate.parentFile
        }
        error("could not locate the repository root from ${File("").absolutePath}")
    }
}
